apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: interactive-gpu
  namespace: robot-learning
spec:
  runtimeRef:
    name: torch-distributed
  trainer:
    image: 916780037007.dkr.ecr.us-east-1.amazonaws.com/ethroboticsclub/pytorch:sha-d866de5
    command:
      - /bin/bash
      - -lc
      - |
        cp /job-files/main.sh /tmp/main.sh
        chmod +x /tmp/main.sh
        exec /tmp/main.sh
    numNodes: 1
    resourcesPerNode:
      requests:
        cpu: "1"
        memory: "4Gi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "8"
        memory: "16Gi"
        nvidia.com/gpu: "1"
  podTemplateOverrides:
    - targetJobs:
        - name: node
      spec:
        serviceAccountName: training-sa
        nodeSelector:
          karpenter.sh/nodepool: gpul
          node-tier: gpul
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        volumes:
          - name: job-files
            configMap:
              name: interactive-gpu-files
              defaultMode: 0755
        containers:
          - name: node
            volumeMounts:
              - name: job-files
                mountPath: /job-files
                readOnly: true
