apiVersion: v1
kind: PersistentVolume
metadata:
  name: groot-finetune-data
spec:
  mountOptions:
    - allow-other
    - uid=1001
    - gid=1001
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    name: groot-finetune-data
    namespace: humanoid
  csi:
    driver: s3.csi.aws.com
    volumeHandle: groot-finetune-data
    volumeAttributes:
      bucketName: ethrc-ml-data-916780037007
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: groot-finetune-checkpoints
spec:
  mountOptions:
    - allow-other
    - uid=1001
    - gid=1001
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    name: groot-finetune-checkpoints
    namespace: humanoid
  csi:
    driver: s3.csi.aws.com
    volumeHandle: groot-finetune-checkpoints
    volumeAttributes:
      bucketName: ethrc-ml-data-916780037007
