apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: groot-finetune-data-2
  namespace: humanoid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: groot-finetune-checkpoints-2
  namespace: humanoid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
