apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: groot-finetune-data-3
  namespace: humanoid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: groot-finetune-checkpoints-3
  namespace: humanoid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
