apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: groot-finetune-data
  namespace: humanoid
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: groot-finetune-checkpoints
  namespace: humanoid
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
