apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: sample-training
  namespace: humanoid
spec:
  runtimeRef:
    name: torch-distributed
  trainer:
    image: 916780037007.dkr.ecr.us-east-1.amazonaws.com/ethroboticsclub/pytorch:sha-d866de5
    command:
      - /bin/bash
      - -c
      - curl https://raw.githubusercontent.com/ETHRoboticsClub/Hydra/refs/heads/humanoid/gpu-smoke-test/sample/training/run.sh -o /tmp/run.sh && bash /tmp/run.sh
    numNodes: 1
    resourcesPerNode:
      requests:
        nvidia.com/gpu: "1"
      limits:
        nvidia.com/gpu: "1"
  podTemplateOverrides:
    - targetJobs:
        - name: node
      spec:
        serviceAccountName: training-sa
        nodeSelector:
          karpenter.sh/nodepool: gpus
          node-tier: gpus
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: testing1-data
          - name: checkpoints
            persistentVolumeClaim:
              claimName: testing1-checkpoints
        containers:
          - name: node
            volumeMounts:
              - name: data
                mountPath: /data
              - name: checkpoints
                mountPath: /checkpoints
