apiVersion: v1
kind: PersistentVolume
metadata:
  name: testing1-data
spec:
  mountOptions:
    - allow-other
    - uid=1001
    - gid=1001
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    name: testing1-data
    namespace: robot-learning
  csi:
    driver: s3.csi.aws.com
    volumeHandle: testing1-data
    volumeAttributes:
      bucketName: ethrc-ml-data-916780037007
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: testing1-checkpoints
spec:
  mountOptions:
    - allow-other
    - uid=1001
    - gid=1001
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    name: testing1-checkpoints
    namespace: robot-learning
  csi:
    driver: s3.csi.aws.com
    volumeHandle: testing1-checkpoints
    volumeAttributes:
      bucketName: ethrc-ml-data-916780037007
