apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testing1-data
  namespace: humanoid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testing1-checkpoints
  namespace: humanoid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi