apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: interactive-gpu
  namespace: robot-learning
spec:
  runtimeRef:
    name: torch-distributed
  trainer:
    image: 916780037007.dkr.ecr.us-east-1.amazonaws.com/ethroboticsclub/pytorch:sha-d866de5
    env:
      - name: NVIDIA_VISIBLE_DEVICES
        value: all
      - name: WANDB_API_KEY
        valueFrom:
          secretKeyRef:
            name: wandb-secret
            key: WANDB_API_KEY
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            name: hf-secret
            key: HF_TOKEN
    command:
      - /bin/bash
      - -lc
      - |
        cp /job-files/main.sh /tmp/main.sh
        chmod +x /tmp/main.sh
        exec /tmp/main.sh
    numNodes: 1
    resourcesPerNode:
      requests:
        cpu: "1"
        memory: "320Gi"
        nvidia.com/gpu: "4"
      limits:
        cpu: "8"
        memory: "384Gi"
        nvidia.com/gpu: "4"
  podTemplateOverrides:
    - targetJobs:
        - name: node
      spec:
        serviceAccountName: training-sa
        nodeSelector:
          karpenter.sh/nodepool: gpul
          node-tier: gpul
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: act-data
          - name: checkpoints
            persistentVolumeClaim:
              claimName: act-checkpoints
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 8Gi
          - name: wandb-secret
            secret:
              secretName: wandb-secret
          - name: hf-secret
            secret:
              secretName: hf-secret
          - name: job-files
            configMap:
              name: interactive-gpu-files
              defaultMode: 0755
        containers:
          - name: node
            volumeMounts:
              - name: data
                mountPath: /data
              - name: checkpoints
                mountPath: /checkpoints
              - name: dshm
                mountPath: /dev/shm
              - name: wandb-secret
                mountPath: /var/run/secrets/wandb
                readOnly: true
              - name: hf-secret
                mountPath: /var/run/secrets/hf
                readOnly: true
              - name: job-files
                mountPath: /job-files
                readOnly: true
