apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lucafrat-gpu-test-data
  namespace: humanoid
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lucafrat-gpu-test-checkpoints
  namespace: humanoid
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
