apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: act-training
  namespace: robot-learning
spec:
  runtimeRef:
    name: torch-distributed
  trainer:
    image: 916780037007.dkr.ecr.us-east-1.amazonaws.com/ethroboticsclub/pytorch:sha-d866de5
    command:
      - /bin/bash
      - -c
      - git clone https://github.com/ETHRoboticsClub/Hydra.git /tmp/hydra && cd /tmp/hydra/robot-learning/act/run/ && bash entrypoint.sh
    numNodes: 1
    resourcesPerNode:
      requests:
        cpu: "1"
        memory: "4Gi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "8"
        memory: "16Gi"
        nvidia.com/gpu: "1"
  podTemplateOverrides:
    - targetJobs:
        - name: node
      spec:
        serviceAccountName: training-sa
        nodeSelector:
          karpenter.sh/nodepool: gpus
          node-tier: gpus
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: act-data
          - name: checkpoints
            persistentVolumeClaim:
              claimName: act-checkpoints
        containers:
          - name: node
            volumeMounts:
              - name: data
                mountPath: /data
              - name: checkpoints
                mountPath: /checkpoints
