apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: act-training
  namespace: robot-learning
spec:
  runtimeRef:
    name: torch-distributed
  trainer:
    image: pytorch/pytorch:2.10.0-cuda13.0-cudnn9-runtime
    command: ["/bin/bash", "/workspace/run.sh"]
    args:
      - --dataset.repo_id=/dataset
      - --dataset.root=/data
      - --dataset.local_files_only=true
      - --policy.type=act
      - --output_dir=/checkpoints/act
      - --job_name=act_training
      - --policy.device=cuda
    numNodes: 1
    resourcesPerNode:
      requests:
        nvidia.com/gpu: "1"
      limits:
        nvidia.com/gpu: "1"
  podTemplateOverrides:
    - targetJobs:
        - name: node
      spec:
        nodeSelector:
          karpenter.sh/nodepool: gpus
          node-tier: gpus
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: testing1-data
          - name: checkpoints
            persistentVolumeClaim:
              claimName: testing1-checkpoints
        containers:
          - name: node
            volumeMounts:
              - name: data
                mountPath: /data
              - name: checkpoints
                mountPath: /checkpoints
