apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testing1-checkpoints
  namespace: robot-learning
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: gp3
  resources:
    requests:
      storage: 50Gi