apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: inference-server
  namespace: robot-learning
spec:
  predictor:
    pytorch:
      storageUri: s3://our-bucket/model-artifacts
      resources:
        requests:
          cpu: "2"
          memory: "8Gi"
          nvidia.com/gpu: "1"